name: SmallRye Build

on:
  push:
    branches:
      - "main"
      - "1.x"
      - "2.x"
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [
          { 'version': '17', 'opts': '' },
          { 'version': '21', 'opts': '' },
          { 'version': '23', 'opts': '' }
        ]
    name: build with jdk ${{matrix.java.version}}

    steps:
      - uses: actions/checkout@v4
        name: checkout
      - uses: actions/setup-java@v4
        name: set up jdk ${{matrix.java.version}}
        with:
          distribution: temurin
          java-version: ${{matrix.java.version}}
          cache: maven
      - name: validate format
        run: ./mvnw -s .build/maven-ci-settings.xml -f pom.xml -B -pl '!vertx-mutiny-clients-bom' ${{matrix.java.opts}} formatter:validate
      - name: build with maven
        run: ./mvnw -s .build/maven-ci-settings.xml -f pom.xml -B verify ${{matrix.java.opts}}
